config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :surveys
  resources :contacts
  devise_for :users
  resources :users
  resources :contacts
  get 'response', to: 'response#show'
  root 'welcome#index'
  # resource :welcome, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FalconMx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">FALCON</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active ml-5 pl-5">
            <%= link_to 'Inicio', root_path, class: 'nav-link' %>
          </li>
        </ul>
        <%= link_to 'Directorio De Ayuda', contacts_path, class: 'btn btn-outline-primary my-2 my-sm-0 mr-2' %>

        <% if !user_signed_in? %>
          <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-outline-primary my-2 my-sm-0' %>
        <% else %>
          <% if current_user.is_admin? %>
            <%= link_to 'Investigadores', users_path, class: 'btn btn-outline-primary my-2 my-sm-0 mr-2' %>
            <%= link_to 'Formularios', surveys_path, class: 'btn btn-outline-primary my-2 my-sm-0 mr-2' %>
            <%= link_to 'Resultados', questions_path, class: 'btn btn-outline-primary my-2 my-sm-0 mr-2' %>
          <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary my-2 my-sm-0' %>
        <% end %>
      </div>
    </nav>

    <div class="container-fluid text-center">
      <%= yield %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!--footer starts from here-->
    <% unless !current_page?(root_path) %>
      <footer class="footer bg-secondary">
        <div class="container bottom_border">
          <div class="row">
            <div class=" col-sm-4 col-md col-sm-4  col-12 col">
              <h5 class="headin5_amrc col_white_amrc pt2">CONTÁCTANOS</h5>
              <!--headin5_amrc-->
              <p><i class="fa fa-whatsapp"></i> (México) +52 81 8888 2117 </p>
              <p><i class="fa fa fa-mail"></i> falcon.mx@outlook.com  </p>


            </div>


            <div class=" col-sm-4 col-md  col-6 col">
              <h5 class="headin5_amrc col_white_amrc pt2">BRAZIL</h5>
              <p><a href="#">Pending url</a></p>
            </div>


            <div class=" col-sm-4 col-md  col-6 col">
              <h5 class="headin5_amrc col_white_amrc pt2">COLOMBIA</h5>
              <p><a href="#">Pending url</a></p>
            </div>

            <div class=" col-sm-4 col-md  col-6 col">
              <h5 class="headin5_amrc col_white_amrc pt2">NOFAS USA</h5>
              <p>National Organization on Fetal Alcohol Syndrome</p>
              <p><a href="https://www.nofas.org/">https://www.nofas.org/</a></p>
            </div>

          </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>